name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment5-buildroot
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
          - name: Debug SSH Key
            run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c  # Check key length
              echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1  # Print first line
        
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
